### ISSUE TITLE
not working as expected

### ISSUE THREAD

**Issue by costa** [alexgb/guard-konacha#5]
That is, doesn't run as expected, not even once:

```
01:32:19 - INFO - Starting Konacha
[1] guard(main)> Your tests are here:
  http://localhost:3500/
[2012-11-19 01:32:34] INFO  WEBrick 1.3.1
[2012-11-19 01:32:34] INFO  ruby 1.9.3 (2012-10-12) [x86_64-darwin11.4.2]
[2012-11-19 01:32:34] INFO  WEBrick::HTTPServer#start: pid=58831 port=3500
[2012-11-19 01:34:21] WARN  Could not determine content-length of response body. Set content-length of the response or set Response#chunked = true
[2012-11-19 01:34:21] WARN  Could not determine content-length of response body. Set content-length of the response or set Response#chunked = true
```

etc
This is the first time, and I did visit the URL. And then, on file changes, nada.

**Comment by alexgb** [comment]
You're right, recent changes to Guard broke the way child processes were being spawned. Should be fixed now.

**Comment by costa** [comment]
also, you're a dollar short on your regex

**Comment by alexgb** [comment]
Care to enlighten me?

**Comment by costa** [comment]
`watch(%r{^spec/javascripts/.+_spec(\.js|\.js\.coffee)$})`

I've upgraded, but it still doesn't do anything particularly useful. It doesn't run the tests.

**Comment by alexgb** [comment]
`bundle exec rake konacha:run` works for you? What Konacha driver are you using?

**Comment by costa** [comment]
It was probably some quirk of other components, seems working now. Thanks.
